"""empty message

Revision ID: 167a0bbb089b
Revises: d33645f1a4ad
Create Date: 2026-07-30 10:42:37.886006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167a0bbb089b'
down_revision = 'd33645f1a4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
