"""empty message

Revision ID: 69829b382621
Revises: 167a0bbb089b
Create Date: 2026-07-30 12:40:17.026290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69829b382621'
down_revision = '167a0bbb089b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
